services:
  app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
    container_name: ofertilo
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/app
    networks:
      - woodflag_proxy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  database:
    image: library/postgres:18.1-alpine
    container_name: postgresql
    env_file:
      - .env.docker
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    healthcheck:
        test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME:-ofertilo}", "-U", "${DATABASE_USER:-ofertilo}" ]
        timeout: 5s
        retries: 5
        start_period: 60s
    networks:
      - woodflag_proxy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  woodflag_proxy:
    external: true

volumes:
  database_data: