app_localized_controllers:
    resource: '../src/Infrastructure/Controller/Web/'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: cs|en

app_entry_redirect:
    resource: '../src/Infrastructure/Controller/Web/RedirectToLocaleController.php'
    type: attribute